server:
  port: 8081

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    redirect-uri: ${APPLE_REDIRECT_URI}

saerok:
  api:
    base-url: ${SAEROK_API_BASE_URL}
    prefix: /api/v1

unsplash:
  access-key: ${UNSPLASH_ACCESS_KEY}
  app-name: ${UNSPLASH_APP_NAME}
